///|
let metis_noptions = 40

///|
let option_ptype = 0

///|
let option_objtype = 1

///|
let option_ctype = 2

///|
let option_iptype = 3

///|
let option_rtype = 4

///|
let option_dbglvl = 5

///|
let option_niparts = 6

///|
let option_niter = 7

///|
let option_ncuts = 8

///|
let option_seed = 9

///|
let option_ondisk = 10

///|
let option_minconn = 11

///|
let option_contig = 12

///|
let option_compress = 13

///|
let option_ccorder = 14

///|
let option_pfactor = 15

///|
let option_nseps = 16

///|
let option_ufactor = 17

///|
let option_dropedges = 19

///|
let option_no2hop = 20
